services:
  gitlab-enforcer:
    image: tjuerge/gitlab-enforcer
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
