spring:
  application:
    name: gitlab-enforcer
  main:
    banner-mode: "off"

logging:
  level:
    org.springframework: info
    org.vaulttec: info

proxy:
  host:
  port: 3128

enforcer:
  systemHookToken:

gitlab:
  serverUrl:
  personalAccessToken:
  perPage: 100

rules:
  - rule: org.vaulttec.gitlab.enforcer.rule.GroupSettingsRule
    config:
      membership_lock: true
      share_with_group_lock: true
  - rule: org.vaulttec.gitlab.enforcer.rule.ProtectedBranchRule
    config:
      name: master
      push_access_level: 30
      merge_access_level: 40
      unprotect_access_level: 60
  - rule: org.vaulttec.gitlab.enforcer.rule.ProtectedBranchRule
    config:
      name: release/*
      push_access_level: 40
      merge_access_level: 40
      unprotect_access_level: 60
      
