management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - auditevents

proxy:
  host: ${HTTP_PROXY_HOST}
  port: ${HTTP_PROXY_PORT}

enforcer:
  scheduler:
    rate: ${ENFORCER_SCHEDULER_RATE}
  systemHookToken: ${ENFORCER_SYSTEM_HOOK_TOKEN}

gitlab:
  serverUrl: ${GITLAB_SERVER_URL}
  personalAccessToken: ${GITLAB_PERSONAL_ACCESS_TOKEN}
