spring:
  application:
    name: gitlab-enforcer
  main:
    banner-mode: "off"

logging:
  file:
    max-history: 10
  level:
    org.springframework: info
    org.vaulttec: info

proxy:
  host:
  port: 3128

enforcer:
  scheduler:
    enabled: true
    rate: 300000  # 5 min
  auditEventRepositoryCapacity: 1000
  systemHookToken:

gitlab:
  serverUrl:
  personalAccessToken:
  perPage: 100

rules:
  - rule: org.vaulttec.gitlab.enforcer.rule.GroupSettingsRule
    use: once
    config:
      membership_lock: true
      share_with_group_lock: true
      auto_devops_enabled: false
      project_creation_level: maintainer
      subgroup_creation_level: owner
  - rule: org.vaulttec.gitlab.enforcer.rule.ProtectedBranchRule
    use: always
    config:
      skipUserProjects: true
      keepStricterAccessLevel: true
      name: master
      push_access_level: 30
      merge_access_level: 30
  - rule: org.vaulttec.gitlab.enforcer.rule.ProtectedBranchRule
    use: always
    config:
      skipUserProjects: true
      keepStricterAccessLevel: true
      name: release/*
      push_access_level: 40
      merge_access_level: 40
  