name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package -Dskip.docker.build=true

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.x

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        if: github.event_name != 'pull_request'
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            JAR_FILE=target/${{ secrets.APP_NAME }}.jar
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_NAME }}:${{ env.GITHUB_SHA_SHORT }}
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_NAME }}:${{ env.GITHUB_REF_SLUG == 'master' && 'latest' || env.GITHUB_REF_SLUG }}
